### ISSUE TITLE
Reduce GlobalRuleChange

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#2544]
it would be good to remove the use of GlobalRulesChange and replace them with ReplacementEffects or StaticAbilities if able

- [x] alwaysWither ("`All damage is dealt as though its source had wither.`"),  #3491
- [x] manaBurn ("`A player losing unspent mana causes that player to lose that much life.`"), #4818
- [x] noNight ("`It can't become night.`"), This can be a ReplacementEffect with CantHappen #5239
- [x] blankIsChaos("`Each blank roll of the planar dice is a {CHAOS} roll.`"); #2959 
- [x] attackerChoosesBlockers ("`The attacking player chooses how each creature blocks each combat.`") #5458
- [x] onlyOneBlocker ("`No more than one creature can block each combat.`"),
- [x] onlyOneBlockerPerOpponent ("`Each opponent can't block with more than one creature.`"),
- [x] onlyTwoBlockers ("`No more than two creatures can block each combat.`"),

**Comment by Hanmac** [comment]
global rules finally gone
