### ISSUE TITLE
Dependency Layers Meta Issue

### ISSUE THREAD

**Issue by Hanmac** [Card-Forge/forge#5642]
Collection of issues related to "Layer Dependency"
- #1850
- #4108
- #4680
- #4841
- #5636 

Which Layers should be affected?

* 613.1d Layer 4: Type-changing effects are applied.
Cards like Blood Moon
or Graaz, Unstoppable Juggernaut applying to previous non-creatures that got animated
* 613.1f Layer 6: Ability-adding effects, keyword counters, ability-removing effects, and effects that say an object can’t have an ability are applied.
like Cavalry Master that refers to other creatures with abilities
or stuff that makes the card loose all abilities
* 613.4b Layer 7b: Effects that set power and/or toughness to a specific number or value are applied. Effects that refer to the base power and/or toughness of a creature apply in this layer.
Andrios, Roaming Explorer for example, the pump ability otherwise wouldn't make the static ability apply for these cards

for which Layer 4 and unlikely Layer 6 could have ways to cause a dependency Loop

Related Issues:
- Pump Effects might need to use Static Layers too:
#144

**Comment by Hanmac** [comment]
This is important for _Lifecraft Engine_
> Vehicle creatures you control are the chosen creature type in addition to their other types.

For this to work correct, Animate Effects would need to use StaticAbility Layers

@tool4ever @tehdiplomat @Northmoc  I might need some input there
Like if i need to do Animate → StaticAbility, then I don't want all the Effects in the Command Zone :(

**Comment by Hanmac** [comment]
Places that use addChangedCardTypes to be changed for Layer 4 using this as LinkedHashMap:

- StaticAbilityContinuous
- MANABOND CounterType (playtest)
- Bestow (Add Aura Type + Remove CreatureType)
- Reconfigure (Remove Creature Type)
- AnimateEffect (base)
- AmassEffect

**Comment by tool4ever** [comment]
Imo one of the better ressources (not too outdated and lots of examples) is:
https://outsidetheasylum.blog/dependency/

Like the link suggests we might consider implementing it as directed graph, which when visualized might help players and our debugging too.
This one looks promising: https://jgrapht.org/javadoc/org.jgrapht.core/org/jgrapht/alg/cycle/package-summary.html

Here's my rough pseudocode:

```
For Layer X
[...assume all CDA are already applied the same way if really needed]
	while unapplied Statics left
		For each possible pair of Statics {A,B}, {B,A} etc.
		(it's noteworthy that this should be a flat loop instead of recursion after each static)
			store Affected + trait changes of A
			apply B
			// check these three (one is already enough for dependency):
			1. does Static A still exist?
			2. are getAffectedCards/Players still equal?
			3. are the results still the same? This one probably involves some hardcoded param checks, e.g. AddPower$
			(or we apply both with engine and maybe StaticEffect can implement equals to compare?)
			undo B
		build dependency graph and remove all edges that are part of a loop
		find + apply lowest layer timestamp node (static) without outgoing edge
```

I couldn't really think of any better approach with heuristics but I think we can still do it!

**Comment by Hanmac** [comment]
@tool4ever checkout this Repo:
https://github.com/Soothsilver/ContinuousEffectsSandbox

the problem there is that it can't do dependency loop yet

**Comment by Hanmac** [comment]
@tool4ever 
I think the more tricky ones might be trying to have Bestow use Effect Layers because it's a "would be" effect that looks into the future

**Comment by tool4ever** [comment]
> Our Main Problem is the checking "if Applying A first, would that change what B applies to" would require to make a Copy of the Game State first And that could be too complicated

It would certainly be faster if we can do it on the existing game objects:
1. `applyContinuousAbility(A)`
2. `compare B`
3. `game.getStaticEffects().getStaticEffect(A).remove()`

I think the engine could handle it like that, the View would be frozen anyway and the rest is just Tables/Maps being modified.
To compare calling `getAffectedCards` and some `AbilityUtils` stuff should also not touch anything else.

**Comment by Hanmac** [comment]
> the View would be frozen anyway

I don't think the frozen is applied strong enough
for example right now when i can look at top card of library, it does flicker multiple times

**Comment by Hanmac** [comment]
> I also have a branch where players get handled in better order:
> [tool4ever@78fe805](https://github.com/tool4ever/forge/commit/78fe80584698cb8017813ae61d7736a0c28fc380)

my first attempt for this issue would be something like this:

```

sortStaticAbilties(List<StaticAbility> list) {
    result = [];
    result.addAll(sortStaticAbiltiesByTimestampAndDependency(list.filter(CDA));
    result.addAll(sortStaticAbiltiesByTimestampAndDependency(list.filter(NonCDA));
    return result;
}

sortStaticAbiltiesByTimestampAndDependency(List<StaticAbility> list)
{
    if (list.size <= 1) {
        return list;
    }
    // TODO check for dependency
    return list.sortBy(TimeStamp)
}
```

until i noticed that this wouldn't work unless all effects use Static Abilties

**Comment by Hanmac** [comment]
Layer6:

addChangedCardTraits
- StaticAbilityContinous
- [ ] MANABOND CounterType (playtest)
- [ ] AnimateEffectBase
- [ ] Suspected (Can't Block)
- [ ] PlayerKeywords

addChangedCardKeywords
- StaticAbilityContinous
- [ ] Suspected (Menace)
- [ ] Mana Keywords (ManaSpent to cast Spells, give them Keywords)
- [ ] Ability CounterType
- [ ] PumpAllEffect
- [ ] PumpEffect
- [ ] DebuffEffect (when Protection from all Colors is split)
- [ ] ProtectAllEffect
- [ ] ProtectEffect
- [ ] ControlGainEffect
- [ ] ChangeZoneEffect (Uneath)
- [ ] CloneEffect and TokenEffectBase with PumpKeyword
- [ ] Bestow #6811

**Comment by tool4ever** [comment]
I'm also gunning for AnimateSubAbility.
But judges say the effect from it doesn't exist while doing ETB lookahead:
https://old.reddit.com/r/askajudge/comments/1ggxkoo/containment_priest_enduring_creatures/

My current idea in `GameAction.changeZone`:
1. Moved RE
2. check Cause param and create/reuse DetachedCardEffect
3. Remember the moving card onto effect
4. Apply statics, do ChangesZone trigger etc.

So this might actually be good for us to also clean up the multiple code for it in different effects.

**Comment by Hanmac** [comment]
@tool4ever did you comment to the wrong issue?

**Comment by tool4ever** [comment]
Well I guess I can move the details to a sub-issue

**Comment by Hanmac** [comment]
> Imo one of the better ressources (not too outdated and lots of examples) is:
> https://outsidetheasylum.blog/dependency/

I don't understand this case:
> You control Xenograft naming "Zombie", Urborg, Tomb of Yawgmoth, and Kormus Bell. What does Urborg look like?
> It's a 1/1 creature with no creature types.
> In layer 4, the only dependency is Kormus Bell on Urborg, so we apply Xenograft first, not doing anything. Then we apply Urborg, making itself a Swamp, and then Kormus Bell making it a creature.

Doesn't Xenograft depend on Kormus Bell depending on Urborg, Tomb of Yawgmoth?

I think I need to ask a Judge to explain it to me better

**Comment by tool4ever** [comment]
You're thinking "too far" into the future...
But the Judge explains since a dependency is defined as a relation between effects X and Y, you only ever **compare pair-wise** while building a dependency graph.

This is what I tried to express with: "it's noteworthy that this should be a flat loop instead of recursion after each static"
It's a great simplification for our goal. 🚀

- A: _Each creature you control is the chosen type in addition to its other types._
- B: _Each land is a Swamp in addition to its other land types._
- C: _All Swamps are 1/1 black creatures that are still lands._

Now you only check like this:
- Apply A vs. B then A:
  - A still exists ✅
  - Affected stays identical (Empty) ✅
  - A still tries to do the same ✅

\+
- Apply A vs. C then A:
  - A still exists ✅
  - Affected stays identical (Empty) ✅
  - A still tries to do the same ✅

1. ➡ No dependency for _Xenograft_ exists
2. B +C would be checked accordingly[^1]
4. only then you'd make a decision and move on to a new "round"
---

Also important here:
> For all of these questions, the timestamp order of objects/effects is the order they're mentioned in.

➡ If A had the latest you would get the 1/1 Zombie.
> Assume that that there are no permanents on the battlefield other than the ones mentioned.

➡ Or if you already control a Swamp at the start of L4 (via intrinsic / L1 copy / L2 control change) then yes, a dependency would exist because A would "directly" depend on C

Hope that made sense :)

[^1]: It's possible we could skip this step partly in code because if we start from the earliest timestamped effect the first dependency free one we find can be safely applied already? 🤔

**Comment by Hanmac** [comment]
@tool4ever yeah i was asking them directly on twitter too, i just didn't link the post there yet

in my opinion, a much deeper check would make more sense, but so it is easier for us, i think

**Comment by tool4ever** [comment]
I could also fix cases like this:
![Image](https://github.com/user-attachments/assets/8128935a-acef-4d4a-959e-e5e1f6dbd585)

However this requires switching `changedCardTypes` into `HashBasedTable` so it doesn't mess up the insertion order.

Might be something to think about in a follow-up.

**Comment by Hanmac** [comment]
@tool4ever I was thinking about LinkedHashMap

But we need to change the other effects fir this too

**Comment by Hanmac** [comment]
> I discovered yesterday that Blood moon is applied asymmetrically, it only applied to me and not the AI in forge-adventure.


@tool4ever can you look into this?

**Comment by tool4ever** [comment]
can't reproduce, not enough information

**Comment by tool4ever** [comment]
Something like "As long as you control another creature with power 5 or greater CARDNAME gets +1/0." would make it relevant, but to my knowledge it's not been done currently...

**Comment by Hanmac** [comment]
@tool4ever 
A Dependency in Layer 7c
> Phyrexian Ingester exiling Skullbriar with a +1/+1 counter.

https://x.com/IsaacKing314/status/1890507856928972968

This might need to use Unswitched PT, or are we counting on that card in exile can't have SwitchPT?

**Comment by Hanmac** [comment]
Some thought on how to rewrite "Guardian Beast" in removing it from #3307
> noncreature artifacts you control ... and other players can’t gain control of them.

I was asking on how this would work when the Control Effect ends?

https://github.com/Card-Forge/forge/blob/137d87c3dfe36773cd7e05726809386dc65745ea/forge-game/src/main/java/forge/game/ability/effects/ControlGainEffect.java#L90-L101

But then I thought, what if the ControlGainEffect gets updated using Layers? 613.1b Layer 2

Then me losing Control would just remove the Timestamp, and apply the Static Abilities again, and the "CantGainControl" wouldn't apply there 

@tool4ever your thought?

**Comment by tool4ever** [comment]
That's a good point and I agree:
- we need to treat it more like a continuous effect so that even if a CantGainControl is currently active it gets created anyway?
- this means you should be able destroy _Guardian Beast_ later in the turn and then that control change will still get applied?
- likewise if something is already stolen by _Confiscate_ if it then ETBs control should revert?

**Comment by Hanmac** [comment]
> we need to treat it more like a continuous effect

Yeah, that's part of my changes needed for this.

Each Effect, Pump/Animate/GainControl should just create Effect Objects with Static Layers instead

**Comment by Hanmac** [comment]
@tool4ever apropos GainControl, we might need to take a look at GainControlTarget
it is related to `You may choose not to untap CARDNAME during your untap step.` one

**Comment by tool4ever** [comment]
@Hanmac
We could do that KW with `Layer$ CantHappen | Optional$` instead? 💡

**Comment by Hanmac** [comment]
> [@Hanmac](https://github.com/Hanmac) We could do that KW with `Layer$ CantHappen | Optional$` instead? 💡

probably, my part was about "GainControlTarget" that could be removed?
it is for the GUI to keep track on what you choose for the ability?

**Comment by tool4ever** [comment]
yea it's only helper because in some situations it might be difficult to find out otherwise?

**Comment by tool4ever** [comment]
Found this place that also uses it:
https://github.com/Card-Forge/forge/blob/3b8694483c9171ae3a69ed39fe36f2b9af24c304/forge-ai/src/main/java/forge/ai/PlayerControllerAi.java#L937

**Comment by Hanmac** [comment]
> 122.1a A +X/+Y counter on a creature or on a creature card in a zone other than the battlefield, where X and Y are numbers, adds X to that object’s power and Y to that object’s toughness. Similarly, -X/-Y counters subtract from power and toughness. See rule 613.4c.

We might handle +X/+Y and -X/-Y counters a little bit separately and give them static abilities
while doing that, we might allow custom combinations? Like +1/-1?
Only the specific `P1P1` and `M1M1` are used elsewhere

**Comment by Hanmac** [comment]
@tool4ever 
>  Example: Phyrexian Ingester exiling Skullbriar with a +1/+1 counter.

for this case, doesn't it already work without dependency because the counters are already calculated first?

**Comment by tool4ever** [comment]
yea it should, that's why I'm not adding extra checks for that

**Comment by Hanmac** [comment]
> yea it should, that's why I'm not adding extra checks for that

That is also important because i wanted to make +1/+1 counters use a static ability too.
But that probably is only needed if we find a case where it can't be done another way.
